### ISSUE TITLE
custom pattern, concatenation, media query

### ISSUE THREAD

**Issue by sKopheK** [gridonic/postcss-replace#5]
Hello,

I wanted to use this plugin to update URLs after processed CSS file is placed into a subfolder so they still point to proper resources, but found out rules within media queries are processed twice, see example: https://runkit.com/skophek/5ab57de05bbffa0012a596d4

**Comment by peschee** [comment]
@dschenk @mzdr can one of you have a look?

**Comment by mzdr** [comment]
Hey @sKopheK,

thanks for taking the time to report this issue!

The problem is that we loop over _all_ nodes and use `.replaceValues()` regardless if it’s just a declaration or a whole tree of rules. That’s why replacement is happening multiple times in such cases.

https://github.com/gridonic/postcss-replace/blob/2e74c9aaa540620a048e0f44bcc5ac5aa54ece3b/index.js#L40-L50

This is indeed a bug and I’m already fixing it right now. 👍
